spring:
  profiles:
    active: dev
panda:
  jwt:
    location: classpath:panda.jks
    alias: panda
    password: zynf8888
    tokenTTL: 30m
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
#    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.panda.course.controller
  default-flat-param-object: false
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  documents:
    - name: 需求说明
      locations: classpath:markdown/*
      group: 需求
  basic:
    enable: false
    username: abc
    password: 123
  insight:
    enable: true
    service-name: boot3
    secret: S6CsnS8AnPVyb8vvChcdXm4R3p6A6KlAISxBg3IIEgk=
    server: http://localhost:10086
    namespace: spring3




